
@baseUrl = http://localhost:7071/api
#@baseUrl = https://afs-simple-function.azurewebsites.net/api

get {{baseUrl}}/user

###
get {{baseUrl}}/user/1


###
post {{baseUrl}}/user

{
    "id": "10",
    "name": "Irina Pavelkowa",
    "email": "ip@cz.cz"
}

###

post http://localhost:7071/runtime/webhooks/durabletask/orchestrators/on-boarding-orchestrator/

{
    "id": "7"
}

###

GET http://localhost:7071/runtime/webhooks/durabletask/instances/04eef035e0d74eb2afe3722251d619dd

