
@baseUrl = http://localhost:7071/api
#@baseUrl = https://afs-simple-function.azurewebsites.net/api

get {{baseUrl}}/user

###
get {{baseUrl}}/user/1


###
post {{baseUrl}}/user

{
    "id": "5",
    "name": "Irina Pavelkowa",
    "email": "ip@cz.cz"
}